imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: INNMIND
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

old_sound_rabbit_mq:
    connections:
        default:
            host: %rabbitmq_host%
            port: %rabbitmq_port%
            user: %rabbitmq_user%
            password: %rabbitmq_password%
            vhost: /
            lazy: true
    consumers:
        resource:
            connection: default
            exchange_options:
                name: crawler.resource
                type: direct
            queue_options:
                name: crawler.resource
            callback: crawler.resource
