services:
    parser.title_pass:
        class: Innmind\CrawlerBundle\Parser\TitlePass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.uri_pass:
        class: Innmind\CrawlerBundle\Parser\UriPass
        calls:
            - ['setDomainParser', ['@domain_parser']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle, priority: 255 }

    parser.web_app_pass:
        class: Innmind\CrawlerBundle\Parser\WebAppPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.alternates_pass:
        class: Innmind\CrawlerBundle\Parser\AlternatesPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.author_pass:
        class: Innmind\CrawlerBundle\Parser\AuthorPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.canonical_pass:
        class: Innmind\CrawlerBundle\Parser\CanonicalPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.links_pass:
        class: Innmind\CrawlerBundle\Parser\LinksPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.language_pass:
        class: Innmind\CrawlerBundle\Parser\LanguagePass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.rss_pass:
        class: Innmind\CrawlerBundle\Parser\RssPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.charset_pass:
        class: Innmind\CrawlerBundle\Parser\CharsetPass
        calls:
            - ['setValidator', ['@validator']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.content_pass:
        class: Innmind\CrawlerBundle\Parser\ContentPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle, priority: 10 }

    parser.description_pass:
        class: Innmind\CrawlerBundle\Parser\DescriptionPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.android_pass:
        class: Innmind\CrawlerBundle\Parser\AndroidPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.ios_pass:
        class: Innmind\CrawlerBundle\Parser\IosPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.journal_pass:
        class: Innmind\CrawlerBundle\Parser\JournalPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.abbr_pass:
        class: Innmind\CrawlerBundle\Parser\AbbreviationsPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.base_pass:
        class: Innmind\CrawlerBundle\Parser\BasePass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle, priority: 10 }
