services:
    crawler:
        class: Innmind\CrawlerBundle\Crawler
        calls:
            - ['setDispatcher', ['@event_dispatcher']]
            - ['setResourceFactory', ['@resource_factory']]
            - ['setValidator', ['@validator']]
            - ['setLogger', ['@logger']]

    resource_factory:
        class: Innmind\CrawlerBundle\ResourceFactory
