services:
    crawler:
        class: Innmind\CrawlerBundle\Crawler
        calls:
            - ['setDispatcher', ['@event_dispatcher']]
            - ['setResourceFactory', ['@resource_factory']]
            - ['setValidator', ['@validator']]
            - ['setLogger', ['@logger']]
            - ['setStopwatch', ['@stopwatch']]

    resource_factory:
        class: Innmind\CrawlerBundle\ResourceFactory

    domain_parser:
        class: Pdp\Parser
        factory_class: Innmind\CrawlerBundle\DomainParserFactory
        factory_method: make

    uri_resolver:
        class: Innmind\CrawlerBundle\UriResolver
        calls:
            - ['setValidator', ['@validator']]

    normalizer:
        class: Innmind\CrawlerBundle\Normalization\Normalizer

    publisher:
        class: Innmind\CrawlerBundle\Publisher
        calls:
            - ['setNormalizer', ['@normalizer']]
            - ['setLogger', ['@logger']]
            - ['setHost', ['%router.request_context.host%']]

    listener.resource_crawled:
        class: Innmind\CrawlerBundle\Listener\ResourceCrawledListener
        calls:
            - ['setPublisher', ['@publisher']]
        tags:
            - { name: kernel.event_listener, event: resource.processed, method: handle }

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
