services:
    crawler:
        class: Innmind\CrawlerBundle\Crawler
        arguments: ['@event_dispatcher', '@resource_factory', '@validator']

    resource_factory:
        class: Innmind\CrawlerBundle\ResourceFactory
