services:
    crawler:
        class: Innmind\CrawlerBundle\Crawler
        calls:
            - ['setDispatcher', ['@event_dispatcher']]
            - ['setResourceFactory', ['@resource_factory']]
            - ['setValidator', ['@validator']]
            - ['setLogger', ['@logger']]

    resource_factory:
        class: Innmind\CrawlerBundle\ResourceFactory

    domain_parser:
        class: Pdp\Parser
        factory_class: Innmind\CrawlerBundle\DomainParserFactory
        factory_method: make

    uri_resolver:
        class: Innmind\CrawlerBundle\UriResolver
        calls:
            - ['setValidator', ['@validator']]

    parser.title_pass:
        class: Innmind\CrawlerBundle\Parser\TitlePass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.uri_pass:
        class: Innmind\CrawlerBundle\Parser\UriPass
        calls:
            - ['setDomainParser', ['@domain_parser']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle, priority: 255 }

    parser.web_app_pass:
        class: Innmind\CrawlerBundle\Parser\WebAppPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.alternates_pass:
        class: Innmind\CrawlerBundle\Parser\AlternatesPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.author_pass:
        class: Innmind\CrawlerBundle\Parser\AuthorPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.canonical_pass:
        class: Innmind\CrawlerBundle\Parser\CanonicalPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.links_pass:
        class: Innmind\CrawlerBundle\Parser\LinksPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.language_pass:
        class: Innmind\CrawlerBundle\Parser\LanguagePass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.rss_pass:
        class: Innmind\CrawlerBundle\Parser\RssPass
        calls:
            - ['setUriResolver', ['@uri_resolver']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.charset_pass:
        class: Innmind\CrawlerBundle\Parser\CharsetPass
        calls:
            - ['setValidator', ['@validator']]
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }

    parser.content_pass:
        class: Innmind\CrawlerBundle\Parser\ContentPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle, priority: 10 }

    parser.description_pass:
        class: Innmind\CrawlerBundle\Parser\DescriptionPass
        tags:
            - { name: kernel.event_listener, event: resource.crawled, method: handle }
