Innmind\CrawlerBundle\Entity\Resource:
    properties:
        uri:
            - Url: ~
        port:
            - Type:
                type: integer

Innmind\CrawlerBundle\Entity\HtmlPage:
    properties:
        canonical:
            - Url: ~
        rss:
            - Url: ~
        charset:
            - Regex: '/[a-zA-Z\-\d]+/'
        androidURI:
            - Url:
                protocols: ['android-app']
